# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adversary',
            options={'verbose_name_plural': 'adversaries'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
    ]
