# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20171027_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
