# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20171027_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='bookie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.Bookie'),
        ),
        migrations.AlterField(
            model_name='league',
            name='canonical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.League'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
